//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace stj1_masraf_beyan_sureci.Entities {
    
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_Odeme_Formu")]
    public class E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuEntity : FormEntity<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _odencekTutar;
        
        private E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuVREntity _VersionEntity;
        
        private RDEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDEntity, E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDMLEntity> _RD;
        
        private RDCEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCEntity, E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuMLEntity> _ML;
        
        public E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuEntity() {
            this.ML = new MLEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuMLEntity>();
            this.VersionEntity = new E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuVREntity();
            this.RD = new RDEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDEntity, E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCEntity, E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="odencekTutar", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> odencekTutar {
            get {
                return this._odencekTutar;
            }
            set {
                this._odencekTutar = value;
            }
        }
        
        public E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDEntity, E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCEntity, E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuML")]
    public class E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuMLEntity : MLEntity<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _perAdSoyad;
        
        private Bimser.Framework.Domain.DataField<string> _departmanBilgi;
        
        private Bimser.Framework.Domain.DataField<string> _masFormNum;
        
        private Bimser.Framework.Domain.DataField<string> _ibanNo;
        
        private Bimser.Framework.Domain.DataField<string> _TBbadSoyad;
        
        private Bimser.Framework.Domain.DataField<string> _perDep;
        
        private Bimser.Framework.Domain.DataField<string> _TextBoxID;
        
        [ColumnOptionsAttribute(Name="perAdSoyad", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> perAdSoyad {
            get {
                return this._perAdSoyad;
            }
            set {
                this._perAdSoyad = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="departmanBilgi", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> departmanBilgi {
            get {
                return this._departmanBilgi;
            }
            set {
                this._departmanBilgi = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="masFormNum", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> masFormNum {
            get {
                return this._masFormNum;
            }
            set {
                this._masFormNum = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="ibanNo", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> ibanNo {
            get {
                return this._ibanNo;
            }
            set {
                this._ibanNo = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="TBbadSoyad", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> TBbadSoyad {
            get {
                return this._TBbadSoyad;
            }
            set {
                this._TBbadSoyad = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="perDep", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> perDep {
            get {
                return this._perDep;
            }
            set {
                this._perDep = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="TextBoxID", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> TextBoxID {
            get {
                return this._TextBoxID;
            }
            set {
                this._TextBoxID = value;
            }
        }
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuVR")]
    public class E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuVREntity : VersionEntity<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuVREntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDC")]
    public class E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCEntity : RDCEntity<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCEntity, E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCML")]
    public class E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCMLEntity : RDCMLEntity<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRD")]
    public class E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDEntity : RDEntity<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDEntity, E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDML")]
    public class E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDMLEntity : RDMLEntity<E_stj1_masraf_beyan_sureci_Masraf_Odeme_FormuRDMLEntity> {
    }
}




