//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace stj1_masraf_beyan_sureci.Entities {
    
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleri")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleriEntity : FormEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleriEntity> {
        
        private E_stj1_masraf_beyan_sureci_Masraf_tipleriVREntity _VersionEntity;
        
        private RDEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleriRDMLEntity> _RD;
        
        private RDCEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCMLEntity> _RDC;
        
        private GridEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuMLEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLMLEntity> _E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosu;
        
        public E_stj1_masraf_beyan_sureci_Masraf_tipleriEntity() {
            this.VersionEntity = new E_stj1_masraf_beyan_sureci_Masraf_tipleriVREntity();
            this.RD = new RDEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleriRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCMLEntity>();
            this.E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosu = new GridEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuMLEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLMLEntity>();
            this.E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosu.MLEntityEnabled = true;
            this.E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosu.SLEntityEnabled = false;
        }
        
        public E_stj1_masraf_beyan_sureci_Masraf_tipleriVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleriRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public GridEntityCollection<E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuMLEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLMLEntity> E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosu {
            get {
                return this._E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosu;
            }
            set {
                this._E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosu = value;
            }
        }
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosu")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuEntity : GridEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuMLEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLMLEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _IDmasraf;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _maksOdeme;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<bool>> _durumMasrafi;
        
        public E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuEntity() {
        }
        
        [ColumnOptionsAttribute(Name="IDmasraf", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> IDmasraf {
            get {
                return this._IDmasraf;
            }
            set {
                this._IDmasraf = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="maksOdeme", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> maksOdeme {
            get {
                return this._maksOdeme;
            }
            set {
                this._maksOdeme = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="durumMasrafi", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<bool>> durumMasrafi {
            get {
                return this._durumMasrafi;
            }
            set {
                this._durumMasrafi = value;
            }
        }
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuML")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuMLEntity : GridMLEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _tipMasraf;
        
        [ColumnOptionsAttribute(Name="tipMasraf", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> tipMasraf {
            get {
                return this._tipMasraf;
            }
            set {
                this._tipMasraf = value;
            }
        }
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSL")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLEntity : GridSLEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLML")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLMLEntity : GridSLMLEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleri_masrafTablosuSLMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleriVR")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleriVREntity : VersionEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleriVREntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleriRDC")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCEntity : RDCEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCML")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCMLEntity : RDCMLEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleriRD")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleriRDEntity : RDEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDEntity, E_stj1_masraf_beyan_sureci_Masraf_tipleriRDMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_masraf_beyan_sureci_Masraf_tipleriRDML")]
    public class E_stj1_masraf_beyan_sureci_Masraf_tipleriRDMLEntity : RDMLEntity<E_stj1_masraf_beyan_sureci_Masraf_tipleriRDMLEntity> {
    }
}




